### PR TITLE
Updated specs2 and scalaz

### PR DESCRIPTION
**Pull request by etorreborre**
I have refactored most of the test cases and for `RefRemoteSpec` I have used a new functionality in specs2 `3.x` which is a "Fragments Continuation" where we can create new examples on the fly, inside an example.

I would like to use your library in one of your projects but Scalaz 7.1.6 is unfortunately a blocker for us now. If you approve this PR, when do you think you can deploy a new version?

Thanks.

### CODE REVIEW

**Comment by etorreborre** [comment]
Nice, `RefRemoteSpec` is failing on Travis, but I have no idea why...

**Comment by edgarmueller** [comment]
Wow, thanks for your efforts! I'll try to have a look at the failing test case. Given that, I'll probably be able to include your changes and deploy a new version until the end of this week.

**Comment by edgarmueller** [comment]
Hm, got no clue why Travis fails, I created issue #33 to track that as a separate issue for now in order to merge your PR. Thanks!

**Comment by etorreborre** [comment]
Thanks. I am really annoyed by this failure especially because the error message should display an exception but nothing get printed. If you can reproduce it and get anything more informative, please tell me.

**Pull request merged**
