### PR TITLE
Updated specs2 to 3.7.2

### PR DESCRIPTION
**Pull request by etorreborre**
We *should* have more details about the failing spec in Travis :game_die:

### CODE REVIEW

**Comment by etorreborre** [comment]
I am still working on that. I will try to update this PR tomorrow.

**Comment by edgarmueller** [comment]
Ok, I didn't have much time yet to look into this (and probably won't). Thank you

**Comment by etorreborre** [comment]
I am actually not convinced that the tests were running properly before. For example:

https://travis-ci.org/eclipsesource/play-json-schema-validator/builds/112941850#L1105

Shouldn't this display `+ ref within ref valid`, `+ ref within ref invalid` and so on?

**Comment by etorreborre** [comment]
For now I have just skipped that test if it doesn't pass on Travis to make the build :green_apple:. That's cheating, I know :-).

**Comment by etorreborre** [comment]
BTW if you have time to release today that would be great! Thanks.

**Comment by etorreborre** [comment]
Last thing: you can notice how the [build times](https://travis-ci.org/eclipsesource/play-json-schema-validator/pull_requests) have gone down by doing some caching on Travis.

**Comment by edgarmueller** [comment]
Before PR #32 each test that read a JSON file just outputted a single 'validate' message, which was a bit tedious to debug of course in case one or more of the tests failed. Hence, the descriptions of each executed test case like `+ ref within ref valid` was not printed. 
I'll release a version later today then.
Thanks

**Comment by edgarmueller** [comment]
FYI: I've released 0.6.4. Let me know if you need anything else. Thanks

**Comment by etorreborre** [comment]
Thanks, I'll try it.

**Pull request merged**
